name: 'Deploy to Firebase'
author: 'Douglas Fornaro <DouglasCF@github.com>'
description: 'A GitHub Action to deploy to Firebase'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'red'
